version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Docker/go/Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - ".:/app"
    command: air
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todos_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
